---
version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - "$HOME/.deepforge/data:/data/db"
  server:
    environment:
      - "MONGO_URI=mongodb://mongo:27017/deepforge"
      - "DEEPFORGE_HOST=https://dev.deepforge.org"
      - "DEEPFORGE_INTERACTIVE_COMPUTE_HOST=https://dev-compute.deepforge.org"
      - "DEEPFORGE_PUBLIC_KEY=/token_keys/public_key"
      - "DEEPFORGE_PRIVATE_KEY=/token_keys/private_key"
    image: deepforge/kitchen-sink:latest
    ports:
      - "8888:8888"
      - "8889:8889"
    volumes:
      - "$HOME/.deepforge/blob:/data/blob"
      - "${TOKEN_KEYS_DIR}:/token_keys"
    depends_on:
      - mongo
