services:
  server:
    entrypoint: /.deployment/dev-entrypoint.sh
    environment:
      - "DEEPFORGE_HOST=https://dev.deepforge.org"
      - "DEEPFORGE_INTERACTIVE_COMPUTE_HOST=https://dev-compute.deepforge.org"
    volumes:
      - "${DEEPFORGE_DEPLOYMENT_DIR}:/.deployment"
      - "${DEEPFORGE_DEPLOYMENT_DIR}/../config/components.json:/deepforge/config/components.json"

  server_stable:
    entrypoint: /.deployment/dev-entrypoint.sh
    environment:
      - "MONGO_URI=mongodb://mongo:27017/deepforge"
      - "DEEPFORGE_HOST=https://editor.deepforge.org"
      - "DEEPFORGE_INTERACTIVE_COMPUTE_HOST=https://compute.deepforge.org"
      - "DEEPFORGE_PUBLIC_KEY=/token_keys/public_key"
      - "DEEPFORGE_PRIVATE_KEY=/token_keys/private_key"
    image: deepforge/kitchen-sink:stable
    ports:
      - "9000:8888"
    volumes:
      - "$HOME/.deepforge/blob:/data/blob"
      - "${TOKEN_KEYS_DIR}:/token_keys"
      - "${DEEPFORGE_DEPLOYMENT_DIR}:/.deployment"
      - "${DEEPFORGE_DEPLOYMENT_DIR}/../config/components.json:/deepforge/config/components.json"
    depends_on:
      - mongo

  language_servers:
    image: deepforge/language-servers:latest
    ports:
      - "8890:3000"
    volumes:
      -  "${DEEPFORGE_DEPLOYMENT_DIR}/../language-servers.yml:/root/language-servers.yml"
      - "/tmp/py-models:/tmp/py-models"
    depends_on:
      - server
      - server_stable
